### ISSUE TITLE
Handle Payment Success

### ISSUE THREAD

**Issue by atulmy** [andrewangelle/react-paypal-button#5]
The button works great however I was wondering how to make sure we have the callback/handle payment success with identifier to cross check on server side?

**Comment by atulmy** [comment]
For example the [`onApprove`](https://github.com/paypal/paypal-checkout-components/blob/master/demo/react.htm#L26) method:

```
onApprove = (data, actions) => {
  console.log('onApprove')
  console.log(data)
  console.log(actions)
}
```

```
<Button
  onApprove={onApprove}
/>
```
will return following info:
```
{
  intent: "sale"
  orderID: "x"
  payerID: "x"
  paymentID: "x"
  paymentToken: "x"
  returnUrl: "https://www.paypal.com/checkoutnow/error?paymentId=x"
}
```

**Comment by andrewangelle** [comment]
@atulmy Thanks for inquiring. I briefly looked into this and it seems fairly straight forward for me to add an `onSuccess` callback that returns the transaction data object to the consumer of Button. 

I'll look more into this and do my best to implement the feature within the next week or so. 
Since It will require a minor version bump, I'll keep the issue open and ping you once it is released.

**Comment by atulmy** [comment]
Meanwhile I had extracted the button into a component to get it working with `onAuthorize` as a `prop`:

```javascript
import paypal from 'paypal-checkout'

const Button = paypal.Button.driver('react', { React, ReactDOM })

class PayPalButton extends React.Component {
  ...
  render() {
    const { onAuthorize, style } = this.props
    return(
      <Button
        ...
        onAuthorize={onAuthorize}
        style={style}
      />
    )
  }
}
```

```javascript
import PayPalButton from './PayPalButton'

...
<PayPalButton
  ...
  onAuthorize={this.onAuthorize}
  style={{
    color: 'silver',
    shape: 'pill'
  }}
/>
...
```
